stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  only:
    - dev # I noticed you're deploying from the dev branch
  before_script:
    - apk update && apk add openssh-client git # Install SSH client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Deploying application..."
    - ssh $SERVER_USERNAME@$SERVER_HOST "cd /var/opt/gbookingfebe/ && git pull origin dev && npm install && pm2 restart ecosystem.config.js"
