stages:
  - deploy

deploy:
  stage: deploy
  only:
    - dev # or master, depending on your default branch
  script:
    - echo "Deploying application..."
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh $SERVER_USERNAME@$SERVER_HOST "cd /var/opt/gbookingfebe/ && git pull origin dev && npm install && pm2 restart gbooking"
